services:
    smoke-api-test:
      image: api:v1
      build:
        context: .  # текущая директория
        dockerfile: Dockerfile # указание докер файла, на котором создастся образ
      volumes:
        - ./:/usr/workspace # <local_folder>:<container_folder>
      command: /bin/sh -c "STAGE=$$STAGE pytest -n=3 -m=$$SUITE -o log_cli=true"  # переменная будет равна значению из environment
      env_file:
        - .env
      environment:
          STAGE: ${STAGE}  # внутри контейнера переменная окружения будет приниматься извне
          SUITE: ${SUITE:-smoke}
      tty: true